---
title: "Olive Oil Taste Test Pilot Data"
output: pdf_document
date: '2022-03-15'
---


```{r load packages, warning=FALSE, message = FALSE, echo=FALSE}
#tinytex::install_tinytex()

library(data.table)
library(ggplot2)
library(reshape)
library(readxl)
library(stringr)
library(stargazer)
library(reshape)
```

```{r import data, echo=FALSE}
filename <- "./data/final_data/de-identified_data.xlsx"

data <- data.table(read_excel(filename, 
                   sheet = 'All', skip = 0, col_names = TRUE))
```
```{r Data Cleanup, echo=FALSE}
# Removing unnecessary columns
data[,c("admin","s_agreement", "agree_to_taste"):=NULL]

# Add `tested` variable, Tested if better_taste != NaN.
# 1 = Tested, 0 = Not tested yet
data[, tested := ifelse(is.na(better_taste) == FALSE, 1, 0)]

# 1 if participant tasted olive oil more than once prior to experiment, 0 otherwise
data[, tasting_count := ifelse(tasting_count >= 2, 1, 0)]

# 1 if participant tested positive for covid in the past two years, 0 otherwise
data[, covid := ifelse(covid == "Yes", 1, 0)]

# 1 if participant azzigned to treatment, 0 otherwise
data[, azzignment := ifelse(azzignment == "treatment", 1, 0)]

# 1 if participant said oo 2 had a better smell, 0 if participant said oo 1 had a better smell, NA if same
#data[, better_smell := ifelse(better_smell > 1, 1, 0, na=TRUE)]
data[, better_smell := ifelse(better_smell==2, 1, ifelse(better_smell==1, 0, NaN))]
data[, more_bitter := ifelse(more_bitter==2, 1, ifelse(more_bitter==1, 0, NaN))]
data[, better_taste := ifelse(better_taste==2, 1, ifelse(better_taste==1, 0, NaN))]
```


```{r check azzignment ratios, warning=FALSE, echo=FALSE}
stargazer(data, type='text')
```




```{r check first olive oil 1 vs 2 ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to taste OO #1 or OO #2 first by `azzignment`.
only_tested <- data[(tested==1), ]

melted_first_oo_data <- data.table(melt(only_tested[, table(azzignment, by=(first_oo))], id=c("azzignment")))

melted_first_oo_data[, azzignment := ifelse(azzignment==0, "Factual Message\n(Control)", "Marketing Message\n(Treatment)")]
melted_first_oo_data[, height := c(26, 43, 16, 38)]
melted_first_oo_data[, height := c(43, 38, 26, 16)]
# Build title.
first_oo_title = paste(only_tested[, round(mean(first_oo==0),2)*100], '% of all participants assigned to smell and sip olive oil #1 first.', sep='')
first_oo_title = 'Binomial randomization of first olive oil produced\nuneven partitions within message groups.'
# Build Plot.
ggplot(melted_first_oo_data, aes(fill=as.factor(by), y=value, x=azzignment)) + 
  geom_bar(position="stack", stat="identity") +
  ggtitle(first_oo_title) +
  xlab("Participant Assignment") + ylab("Number of Participants") + 
  geom_col() +
  geom_text(aes(y = height, label = value), vjust = 1.5, colour = "white") +
  
  scale_fill_discrete(name = "", labels = c("Tasted OO #1 First", "Tasted OO #2 First")) +
  ylim(0, 50)

```

```{r, fig.cap="Full Model Correlation", fig.width=6, fig.height=4}
numeric_data <- data[, c("sex", "tasting_count", "covid", "azzignment", "first_oo", "better_smell", "more_bitter", "better_taste")]

# Create a correlation dataframe
raw_corr_data <- cor(numeric_data)
rounded_corr_data <- round(raw_corr_data, 2)

# Get upper triangle of the correlation dataframe
get_upper_tri <- function(corr_matrix){
  corr_matrix[lower.tri(corr_matrix)]<- NA
  return(corr_matrix)}

upper_tri <- get_upper_tri(rounded_corr_data)

melted_cor_matrix <- melt(upper_tri, na.rm = TRUE) # flatten correlation dataframe

# Generate correlation heatmap
full_model_corr_matrix <- ggplot(data = melted_cor_matrix, aes(X2, X1, fill = value)) + 
  geom_tile(color = "white") +
  labs(title = "Full Model Correlation Matrix", x='', y='') +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1,1), space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 11)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 9.5, hjust = 1)) +
  theme(axis.text.y = element_text(size = 9.5)) +
  theme(legend.key.size = unit(1, 'cm')) +
  coord_fixed()
full_model_corr_matrix # Print correlation heat map
```