---
title: "Olive Oil Taste Test Pilot Data"
output: pdf_document
date: '2022-03-15'
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, warning=FALSE, message = FALSE, echo=FALSE}
# tinytex::install_tinytex()

library(data.table)
library(ggplot2)
library(reshape)
library(readxl)
library(stringr)
```

```{r import data, echo=FALSE}
filename <- "randomized_Olive Oil Experiment Participant List_3_15_22.xlsx"

data <- read_excel(paste("../data/randomized_participant_data/", filename, sep=""), 
                   sheet = 'Sheet1', skip = 0, col_names = TRUE)
data <- data.table(data)

# Add `tested` variable, Tested if Signed Agreement != NaN.
data[, tested := ifelse(is.na(smell_outcome) == FALSE, 'Tested', 'Not Tested Yet')]
```

# 50 Participants Tested, 37 More To Go As Of 3/15/22.

```{r check azzignment ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to control/treatment by `tested`.
melted_azzignment_data <- data.table(melt(data[, table(tested, by=(azzignment))], id=c("tested")))

# Build title.
azzignment_title = paste(data[, round(mean(azzignment=='treatment'),2)*100], '% of all participants assigned to Treatment.', sep='')

# Build Plot.
ggplot(melted_azzignment_data, aes(fill=as.factor(by), y=value, x=tested)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(azzignment_title) +
  scale_x_discrete(name = "", labels = c('Not Tested', 'Tested'), guide = guide_axis(angle = 0)) +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c('Recieved Factual Message', 'Recieved Marketing Message'), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 3)) +
  geom_text(aes(x=c(.77, 1.77, 1.23, 2.23), 
                label = melted_azzignment_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```

```{r check first olive oil 1 vs 2 ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to taste OO #1 or OO #2 first by `tested`.
melted_first_oo_data <- data.table(melt(data[, table(tested, by=(first_oo))], id=c("tested")))

# Build title.
first_oo_title = paste(data[, round(mean(first_oo==0),2)*100], '% of all participants assigned to smell and sip olive oil #1 first.', sep='')

# Build Plot.
ggplot(melted_first_oo_data, aes(fill=as.factor(by), y=value, x=tested)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(first_oo_title) +
  scale_x_discrete(name = "", labels = c('Not Tested', 'Tested'), guide = guide_axis(angle = 0)) +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c("Tasted Olive Oil #1 First", "Tasted Olive Oil #2 First"), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 2)) +
  geom_text(aes(x=c(.77, 1.77, 1.23, 2.23), 
                label = melted_first_oo_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```

# Covariate Balance Check

```{r import pre experiment survey data, echo=FALSE}
filename <- "CLEAN_PreExperiment_Survey_3_16_22.xlsx"

data <- read_excel(paste("./", filename, sep=""), skip = 0, col_names = TRUE)
data <- data.table(data)

# Adding an adjusted birth country column
data[, adj_birth_country := ifelse(country_of_birth=='USA', 'USA', ifelse(country_of_birth=='Turkey', 'Turkey', 'Other'))]

# Adding an adjusted age range column
data[, adj_age := ifelse(age=='18 to 24' | age=='25 to 34', '18 to 34',
                         ifelse(age =='35 to 44' | age=='45 to 54', '35 to 54','55 or older'))]

```


```{r check country_of_birth ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to control/treatment by `country_of_birth`.
melted_country_of_birth_data <- data.table(melt(data[, table(adj_birth_country, by=(azzignment))], id=c("country_of_birth")))

# Build title.
country_of_birth_title = "Covariate Check on Country of Birth"

# Build Plot.
ggplot(melted_country_of_birth_data, aes(fill=as.factor(by), y=value, x=adj_birth_country)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(country_of_birth_title) +
  scale_x_discrete(name = "Country of Birth") +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c('Recieved Factual Message', 'Recieved Marketing Message'), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 1)) +
  geom_text(aes(x=c(.77, 1.77, 2.77, 1.23, 2.23, 3.23), 
                label = melted_country_of_birth_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```

```{r check age ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to control/treatment by `covid`.
melted_age_data <- data.table(melt(data[, table(adj_age, by=(azzignment))], id=c("adj_age")))

# Build title.
age_title = "Covariate Check on Age Ranges"

# Build Plot.
ggplot(melted_age_data, aes(fill=as.factor(by), y=value, x=adj_age)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(age_title) +
  scale_x_discrete(name = "Participant Age Range") +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c('Recieved Factual Message', 'Recieved Marketing Message'), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 1)) +
  geom_text(aes(x=c(.77, 1.77, 2.77, 1.23, 2.23, 3.23), 
                label = melted_age_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```

```{r check covid ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to control/treatment by `covid`.
melted_covid_data <- data.table(melt(data[, table(covid, by=(azzignment))], id=c("covid")))

# Build title.
covid_title = "Covariate Check on Covid"

# Build Plot.
ggplot(melted_covid_data, aes(fill=as.factor(by), y=value, x=covid)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(covid_title) +
  scale_x_discrete(name = "", labels = c('Did Not Have COVID-19', 'Had COVID-19'), guide = guide_axis(angle = 0)) +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c("Tasted Olive Oil #1 First", "Tasted Olive Oil #2 First"), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 2)) +
  geom_text(aes(x=c(.77, 1.77, 1.23, 2.23), 
                label = melted_covid_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```


```{r check no of previous olive oil tastings ratios, warning=FALSE, echo=FALSE}
# Get data.table of number of participants azzigned to control/treatment by `oo_count`.
melted_oo_count_data <- data.table(melt(data[, table(oo_count, by=(azzignment))], id=c("oo_count")))

# Build title.
oo_count_title = "Covariate Check on Number of Times Tasted Olive Oil"

# Build Plot.
ggplot(melted_oo_count_data, aes(fill=as.factor(by), y=value, x=oo_count)) + 
  geom_bar(stat = "identity",
        aes(fill = factor(by)),
        position = position_dodge(width = 0.9)) +
  ggtitle(oo_count_title) +
  scale_x_discrete(name = "", labels = c('0-1 Prior Tastings', '2+ Prior Tastings'), guide = guide_axis(angle = 0)) +
  ylab("Number of Participants") + 
  scale_fill_manual(name = "", 
                    labels = c("Tasted Olive Oil #1 First", "Tasted Olive Oil #2 First"), 
                    values=c("#bad824", "#5a8a00"))+
  scale_y_continuous(expand = c(0, 0, 0, 5)) +
  geom_text(aes(x=c(.77, 1.77, 1.23, 2.23), 
                label = melted_oo_count_data[, value],
                family = "Times"),
            vjust=-.5) +
  theme_bw() + 
  theme(text=element_text(family="Times")) +
  theme(title = element_text(size = 12)) + 
  theme(axis.title = element_text(size = 10))
```


